# Generated by Django 3.2.13 on 2022-05-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memestructure', '0002_auto_20220511_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='author',
            field=models.CharField(default='lol', max_length=150),
            preserve_default=False,
        ),
    ]
