# Generated by Django 3.2.13 on 2022-05-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memestructure', '0003_meme_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReplyParent', to='memestructure.comment'),
        ),
    ]
