# Generated by Django 3.2.13 on 2022-05-11 08:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memestructure', '0004_alter_reply_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='photo',
            field=models.FileField(null=True, upload_to='images/memephotos', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL),
        ),
    ]
