# Generated by Django 3.2.13 on 2022-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memestructure', '0006_auto_20220511_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/memephotos'),
        ),
    ]
